# Generated by Django 3.2.12 on 2022-02-03 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenRuns',
            fields=[
                ('run_number', models.PositiveIntegerField(help_text='Run number', primary_key=True, serialize=False, verbose_name='Run')),
                ('dataset_express', models.CharField(max_length=150)),
                ('dataset_prompt', models.CharField(blank=True, max_length=150, null=True)),
                ('dataset_rereco', models.CharField(blank=True, max_length=150, null=True)),
                ('dataset_rereco_ul', models.CharField(blank=True, max_length=150, null=True)),
                ('date_retrieved', models.DateField()),
                ('state_express', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('SIGNOFF', 'SignOff')], max_length=9)),
                ('state_prompt', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('SIGNOFF', 'SignOff')], max_length=9)),
                ('state_rereco', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('SIGNOFF', 'SignOff')], max_length=9)),
                ('state_rereco_ul', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('SIGNOFF', 'SignOff')], max_length=9)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
