# Generated by Django 3.2.12 on 2022-02-03 19:21

import certifier.manager
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PixelProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RunReconstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconstruction', models.CharField(choices=[('online', 'Online'), ('express', 'Express'), ('prompt', 'Prompt'), ('rereco', 'ReReco'), ('rerecoul', 'ReRecoUL')], max_length=8)),
                ('is_reference', models.BooleanField(default=False)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oms.omsrun')),
            ],
            options={
                'unique_together': {('run', 'reconstruction')},
            },
        ),
        migrations.CreateModel(
            name='StripProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackingProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackerCertification',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('runreconstruction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='certifier.runreconstruction')),
                ('trackermap', models.CharField(choices=[('exists', 'Exists'), ('missing', 'Missing')], max_length=7)),
                ('pixel', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('excluded', 'Excluded')], max_length=8)),
                ('strip', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('excluded', 'Excluded')], max_length=8)),
                ('tracking', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('excluded', 'Excluded')], max_length=8)),
                ('pixel_lowstat', models.BooleanField(default=False)),
                ('strip_lowstat', models.BooleanField(default=False)),
                ('tracking_lowstat', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('bad_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certifier.badreason')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certifier.dataset')),
                ('pixel_problems', models.ManyToManyField(blank=True, to='certifier.PixelProblem')),
                ('reference_runreconstruction', models.ForeignKey(limit_choices_to={'is_reference': True}, on_delete=django.db.models.deletion.CASCADE, related_name='ref', to='certifier.runreconstruction')),
                ('strip_problems', models.ManyToManyField(blank=True, to='certifier.StripProblem')),
                ('tracking_problems', models.ManyToManyField(blank=True, to='certifier.TrackingProblem')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', certifier.manager.TrackerCertificationManager()),
                ('all_objects', certifier.manager.TrackerCertificationManager(alive_only=False)),
            ],
        ),
    ]
